controller:
    encoder_layers: 1
    decoder_layers: 1
    mlp_layers: 2
    mlp_hidden_size: 64
    hidden_size: 16
    vocab_size: 7
    dropout: 0.0
    source_length: 27
    encoder_length: 27
    decoder_length: 27
