defaults:
    - controller: nasbench101
    - dataset: pretrain_nasbench101
optimizer:
    name: Adam
    lr: 0.01
scheduler:
    name: MultiStepLR
    milestones: [800, 1600, 2400, 3000]
    gamma: 0.1
trainer:
    name: GraphEmbeddingTrainer
    batch_size: 512
    num_epochs: 1
    visualize_step: 400
