defaults:
    - controller: nasbench101
    - dataset: nasbench101
optimizer:
    name: SGD
    lr: 0.1
    momentum: 0.9
scheduler:
    name: MultiStepLR
    milestones: [100, 400]
    gamma: 0.1
trainer:
    batch_size: 1024
    num_epochs: 2
    visualize_step: 400
