defaults:
    - controller: nasbench101
    - dataset: pretrain_nasbench101
optimizer:
    name: SGD
    lr: 2.0
scheduler:
    name: MultiStepLR
    milestones: [20000, 40000, 60000, 70000, ]
    gamma: 0.5
trainer:
    name: GraphEmbeddingTrainer
    batch_size: 512
    num_epochs: 10
    visualize_step: 400
pretrained_model_path:
visualizers:
    -   min_dist: 0.1
        n_neighbors: 16
        angular_rp_forest: True
        metric: cosine
    -   min_dist: 0.5
        n_neighbors: 32
        metric: euclidean
