dataset_path: "./datasets/nasbench/nasbench_only108.tfrecord"
edit_distance: 3
graph_modify_ratio:
  edit_distance_one: 1
  edit_distance_two: 1
  edit_distance_three: 1
max_seq_len: 27
testcase_count: 300
stats:
  min_accuracy: 0.9
  min_diff: 0.7
